version: '3'
services:
  dev:
    image: node:10
    volumes:
      - .:/usr/src/service
    working_dir: /usr/src/service
    command: bash -c "yarn install && yarn run migrate:dev && yarn run dev"
    ports:
      - 3030:3030
